op:
  task: 1
#----------------------------
#  0: Sphere
#  1: Rosenbrock
#  2: Rastrigin
#  3: Michalewicz
#----------------------------
  mask_order: 1
#----------------------------
#  0: linkage tree order
#  1: incremental linkage set (ILS)
#----------------------------


hp:
  dim: 5
  generations: 1000
  bound_min: 0
  bound_max: 5
  init_mean: 2.5
  np_seed: 1
