op:
  task: 1

#----------------------------
#  0: Sphere
#  1: Rosenbrock
#  2: Rastrigin
#  3: Michalewicz
#----------------------------

hp:
  dim: 5
  generations: 100
  bound_min: 0
  bound_max: 1
  init_mean: 0.5
  np_seed: 1